"""Add zoho_id and ZohoSyncState

Revision ID: 9297db8fc21d
Revises: 
Create Date: 2026-04-13 15:28:42.833152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9297db8fc21d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoho_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoho_sync_state_module_name'), 'zoho_sync_state', ['module_name'], unique=True)
    op.add_column('bid', sa.Column('zoho_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_bid_zoho_id'), 'bid', ['zoho_id'], unique=False)
    op.add_column('company', sa.Column('zoho_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_company_zoho_id'), 'company', ['zoho_id'], unique=False)
    op.add_column('project', sa.Column('zoho_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_project_zoho_id'), 'project', ['zoho_id'], unique=False)
    op.add_column('system_error', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('system_error', sa.Column('zoho_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_system_error_entity_id'), 'system_error', ['entity_id'], unique=False)
    op.create_index(op.f('ix_system_error_zoho_id'), 'system_error', ['zoho_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_error_zoho_id'), table_name='system_error')
    op.drop_index(op.f('ix_system_error_entity_id'), table_name='system_error')
    op.drop_column('system_error', 'zoho_id')
    op.drop_column('system_error', 'entity_id')
    op.drop_index(op.f('ix_project_zoho_id'), table_name='project')
    op.drop_column('project', 'zoho_id')
    op.drop_index(op.f('ix_company_zoho_id'), table_name='company')
    op.drop_column('company', 'zoho_id')
    op.drop_index(op.f('ix_bid_zoho_id'), table_name='bid')
    op.drop_column('bid', 'zoho_id')
    op.drop_index(op.f('ix_zoho_sync_state_module_name'), table_name='zoho_sync_state')
    op.drop_table('zoho_sync_state')
    # ### end Alembic commands ###
